#!/bin/bash

# Print the current working directory
echo "Current working directory: $(pwd)"

# Input files
VIDEO1=$(pwd)/$1
VIDEO1L=$(pwd)/"_01L.mp4"
VIDEO2=$(pwd)/$2
VIDEO2L=$(pwd)/"02L.mp4"
OUTPUT=$(pwd)/"output.mp4"
FRAMED_OUTPUT=$(pwd)/"output_framed.mp4"
FRAME=$(pwd)/"512x768.png"
MUSIC=$(pwd)/"$(find . -name "*.mp3" | shuf -n 1)"
FINAL_OUTPUT=$(pwd)/"final_output.mp4"
APPFILE=$(pwd)/"../video_history/copy.mp4"

# Resize VIDEO1 to 512x768
ffmpeg -hide_banner -i "$VIDEO1" -vf scale=512:768,reverse -y "$VIDEO1L"

# Resize VIDEO2 to 512x768
ffmpeg -hide_banner -i "$VIDEO1L" -vf scale=512:768 -y "$VIDEO2L"

# Get the duration of the first video
DURATION=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$VIDEO1")

# Calculate the transition offset (1 second before the end of the first video)
OFFSET=$(echo "$DURATION - 1" | bc)

# Check if the videos have audio streams
HAS_AUDIO_1=$(ffprobe -i "$VIDEO1L" -show_streams -select_streams a -loglevel error -of csv=p=0)
HAS_AUDIO_2=$(ffprobe -i "$VIDEO2L" -show_streams -select_streams a -loglevel error -of csv=p=0)

# Apply the transition using ffmpeg in a Docker container
if [ -n "$HAS_AUDIO_1" ] && [ -n "$HAS_AUDIO_2" ]; then
  # Both videos have audio streams, include audio crossfade
  docker run -i -u $(id -u):$(id -g) -v "$PWD:$PWD" -w "$PWD" mwader/static-ffmpeg:5.1.1 -hide_banner -i "$VIDEO1L" -i "$VIDEO2L" -filter_complex \
  "[0:v][1:v]xfade=transition=fade:duration=1:offset=$OFFSET[v]; \
  [0:a][1:a]acrossfade=duration=1[a]" \
  -map "[v]" -map "[a]" -y "$OUTPUT"
else
  # One or both videos lack audio streams, skip audio crossfade
  docker run -i -u $(id -u):$(id -g) -v "$PWD:$PWD" -w "$PWD" mwader/static-ffmpeg:5.1.1 -hide_banner -i "$VIDEO1L" -i "$VIDEO2L" -filter_complex \
  "[0:v][1:v]xfade=transition=fade:duration=1:offset=$OFFSET[v]" \
  -map "[v]" -y "$OUTPUT"
fi

echo "Output video: $OUTPUT"

# Overlay the transparent PNG frame on the output video
ffmpeg -hide_banner -i "$OUTPUT" -i "$FRAME" -filter_complex \
"[0:v][1:v]overlay=0:0",reverse -y "$FRAMED_OUTPUT"

echo "Framed output video: $FRAMED_OUTPUT"

# Check if the framed output video has an audio stream
HAS_AUDIO_FRAMED=$(ffprobe -i "$FRAMED_OUTPUT" -show_streams -select_streams a -loglevel error -of csv=p=0)

# Add background music with a fade-out effect
if [ -n "$HAS_AUDIO_FRAMED" ]; then
  # Framed video has audio, mix it with the music
  ffmpeg -hide_banner -i "$MUSIC" -i "$FRAMED_OUTPUT" -filter_complex \
  "[0:a]afade=t=out:st=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$FRAMED_OUTPUT" | awk '{print $1-0.75}'):d=0.75[music]; \
  [1:a]volume=1.0[vid]; \
  [vid][music]amix=inputs=2:duration=first:dropout_transition=2[audio]" \
  -map 1:v -map "[audio]" -shortest -y "$FINAL_OUTPUT"
else
  # Framed video has no audio, add music only
  ffmpeg -hide_banner -ss 20 -i "$MUSIC" -i "$FRAMED_OUTPUT" -filter_complex \
  "[0:a]afade=t=out:st=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$FRAMED_OUTPUT" | awk '{print $1-0.75}'):d=0.75[music]" \
  -map 1:v -map "[music]" -shortest -y "$FINAL_OUTPUT"
fi

# Get the current date and time in the desired format
DATE=$(date +"%Y-%m-%d %H:%M:%S")

# Create a filename using the current date and time
date_name="$(date +"%Y-%m-%d_%H-%M-%S").mp4"

# Add the creation_time metadata and save the final output with the new filename
ffmpeg -hide_banner -i "$FINAL_OUTPUT" -c copy -metadata creation_time="$DATE" "$date_name"
cp $FINAL_OUTPUT $APPFILE
echo "Final output video with timestamp: $date_name"